1648996422473	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1648996423270	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1648996915181	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1648996915181	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1648996915185	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1648996915187	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1648997515186	Sync.Service	DEBUG	User-Agent: Firefox/98.0.2 (Linux x86_64) FxSync/1.100.0.20220323001514.desktop
1648997515186	Sync.Service	INFO	Starting sync at 2022-04-03 20:21:55 in browser session AFfLaoP16OVU
1648997515186	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1648997515191	Sync.Status	INFO	Resetting Status.
1648997515191	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1648997515191	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1648997515191	FirefoxAccounts	DEBUG	getOAuthToken enter
1648997515191	FirefoxAccounts	TRACE	getCachedToken returning cached token
1648997515191	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1648997515192	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1648997515192	Sync.SyncAuthManager	INFO	Getting sync key
1648997515192	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1648997515192	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1648997515192	FirefoxAccounts	DEBUG	getOAuthToken enter
1648997515192	FirefoxAccounts	TRACE	getCachedToken returning cached token
1648997515192	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1648997515192	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1648997515192	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1648997515193	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1648997515193	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1648997515193	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1648997515193	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1648997515194	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1648997515194	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1648997515194	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1648997515194	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1648997515196	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1648997515196	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1648997515196	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1648997515196	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1648997515196	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1648997515197	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1648997515200	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
