1649938025507	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1649938025761	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1649938161027	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649938166012	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649940242983	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649940247973	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649940372408	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649940373433	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649941625508	Sync.Service	DEBUG	User-Agent: LibreWolf/99.0 (Linux x86_64) FxSync/1.101.0.20220410100435.desktop
1649941625508	Sync.Service	INFO	Starting sync at 2022-04-14 13:07:05 in browser session EYZeOD56xD0C
1649941625508	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1649941625512	Sync.Status	INFO	Resetting Status.
1649941625512	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1649941625513	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1649941625513	FirefoxAccounts	DEBUG	getOAuthToken enter
1649941625514	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649941625514	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649941625514	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1649941625515	Sync.SyncAuthManager	INFO	Getting sync key
1649941625516	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1649941625516	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1649941625516	FirefoxAccounts	DEBUG	getOAuthToken enter
1649941625516	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649941625516	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649941625516	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1649941625517	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1649941625654	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2153390067 - 
1649941625654	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"<no message>\"  nsresult: \"0x805a1ff3 (<unknown>)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1649941625682	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2153390067 - 
1649941625683	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1649941625683	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1649941625683	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1649941625683	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1649941625684	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1649941625731	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1649941625731	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1649941625731	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1649941625732	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1649941625737	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
