1649945225987	Sync.LogManager	DEBUG	Flushing file log
1649945225990	Sync.LogManager	DEBUG	Log cleanup threshold time: 1649081225990
1649945226001	Sync.LogManager	DEBUG	Done deleting files.
1649945520849	Sync.Service	DEBUG	User-Agent: LibreWolf/99.0 (Linux x86_64) FxSync/1.101.0.20220410100435.desktop
1649945520849	Sync.Service	INFO	Starting sync at 2022-04-14 14:12:00 in browser session EYZeOD56xD0C
1649945520849	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1649945520853	Sync.Status	INFO	Resetting Status.
1649945520853	Sync.Status	DEBUG	Status.service: error.login.failed => success.status_ok
1649945520854	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1649945520854	FirefoxAccounts	DEBUG	getOAuthToken enter
1649945520855	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649945520855	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649945520856	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1649945520857	Sync.SyncAuthManager	INFO	Getting sync key
1649945520860	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1649945520860	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1649945520860	FirefoxAccounts	DEBUG	getOAuthToken enter
1649945520860	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649945520860	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649945520860	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1649945520861	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1649945520916	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2153390067 - 
1649945520916	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"<no message>\"  nsresult: \"0x805a1ff3 (<unknown>)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1649945520917	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2153390067 - 
1649945520917	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1649945520917	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1649945520917	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1649945520918	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1649945520919	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1649945520981	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1649945520982	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
1649945520983	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1649945520983	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 4208478 ms.
1649945520983	Sync.SyncScheduler	DEBUG	Next sync in 4208478 ms. (why=client-backoff-schedule)
1649945520983	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1649945520988	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "<no message>"  nsresult: "0x805a1ff3 (<unknown>)"  location: "<unknown>"  data: no] No traceback available
